import { Box, Flex, Image, Text } from "@chakra-ui/react";
import Head from "next/head";
import { ReactNode } from "react";
import styles from "../styles/Home.module.css";
import Navbar from "./Navbar";

interface Props {
  children: ReactNode;
}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>what2watch - Find Movies and TV Shows!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Flex flexDirection="column" justifyContent="space-between">
        <Box>
          <Navbar />
          <main className={styles.main}>{children}</main>
        </Box>
        <footer className={styles.footer}>
          <Box>
            <a
              href="https://www.themoviedb.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Text>Powered by</Text>
              <span className={styles.logo}>
                <Image
                  src="/tmdb.svg"
                  alt="The Movie Database logo"
                  width="1.5rem"
                />
              </span>
            </a>
          </Box>
        </footer>
      </Flex>
    </>
  );
}
